[input]
exchange_name = "akari_events"

[webhooks]
main = "https://discord.com/api/webhooks/<id>/<token>"
rmb = "https://discord.com/api/webhooks/<id>/<token>"

[roles]
rmb-team = "<role_id>"
endo-team = "<role_id>"
welcome-team = "<role_id>"

[region.testregionia]
default-hook = "main"
default-color = "#44BB12"
rmb = { color = "#AA00BB", hook = "rmb", mentions = ["rmb-team"] }
join = { mentions = ["welcome-team"] }
wajoin = { mentions = ["welcome-team", "endo-team"] }
admit = { mentions = ["endo-team"] }
update = {}
feature = {}
delegate = {}
leave = {}
waleave = {}
found = {}
cte = {}
wacte = {}
apply = {}
resign = {}
wakick = {}